stages:
  - test
  - publish
  - deploy

test:
  stage: test
  image: node:12-alpine
  before_script:
    - npm install
  script:
    - npm run test


publish:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

deploy:
  variables:
    NAMESPACE: sodermalmsskolan-com
  stage: deploy
  image: dtzar/helm-kubectl:3.0.3
  script:
    - kubectl cluster-info
    - helm upgrade --install site ./chart --namespace=$NAMESPACE --set image.tag=$CI_COMMIT_TAG --set image.pullSecret.username=$REGISTRY_USERNAME --set image.pullSecret.password=$REGISTRY_PASSWORD
  only:
    - tags
