apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}-pullsecret
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.image.pullSecret.registry (printf "%s:%s" .Values.image.pullSecret.username .Values.image.pullSecret.password | b64enc) | b64enc | }}
